### ISSUE TITLE
Clicking QC Returns A Java Error

### ISSUE THREAD

**Issue by danshim** [IMFTool/IMFTool#12]
![Screen Shot 2019-03-31 at 2 32 58 PM](https://user-images.githubusercontent.com/1028699/55344116-684dc980-5461-11e9-938e-b8632ae1802a.jpg)

I know photon is another library but it is built, linked and invoked from IMF-Tool - 
It fails every time.

Version: 1.5.285
Java: java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
Mac Mojave 10.14

Cool Tool! Thanks!!!

**Comment by IMFTool** [comment]
Thanks for the report!
Apparently, JRE 12 is not supported by Photon.
I recommend installing Java JDK 1.8. See also [JDK Requirements](https://github.com/Netflix/photon#jdk-requirements)

It's not an IMF Tool issue.
