### ISSUE TITLE
cc:Main[Image or Audio]Sequence error

### ISSUE THREAD

**Issue by mikekrause35pm** [IMFTool/IMFTool#16]
IMF Tool 1.8.360 on PC
When CPLs are checked using https://apps.sandflow.com/imfcplV/ an error is displayed noting: 
"cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'cc:MainImageSequence'."
and/or
"cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'cc:MainAudioSequence'."
Compared to other CPLs, on the surface level it appears `EditRate` is missing.

**Comment by IMFTool** [comment]
`CompositionPlaylist/EditRate` is present in CPLs generated by IMF Tool, as required by ST 2067-3. Can you post or PM an example where it was omitted? 

The error messages of the validator sound like it couldn't find the schema file belonging to the `http://www.smpte-ra.org/ns/2067-2/2020` namespace. I will investigate further.
