### ISSUE TITLE
Length Element Omitted In Asset Map

### ISSUE THREAD

**Issue by anderson1077** [IMFTool/IMFTool#17]
While omission is technically compliant with the spec (ST429-9), IMF-Tool's missing Length element in the Chunk structure, often throws errors in systems that check expected versus actual file size. This would be a welcomed addition to the Asset Map, and a good double check of file integrity before a full hash.

**Comment by IMFTool** [comment]
File size is given bei the (mandatory) Size element of the PKL. No implementation should rely on the presence of an optional element.
