### ISSUE TITLE
OPL support

### ISSUE THREAD

**Issue by cmehay** [IMFTool/IMFTool#18]
I'm looking to create IMF packages from essences files and IMFTool seems to work fine for this, but it seems to not create OPL file and I didn't find any occurrence of OPL in the documentation.  

As there is some OPL occurrence in the source code, I'm wondering if IMFTool can create them (and I didn't find how) or if I have to write my own tool for this ?

Best regards

**Comment by IMFTool** [comment]
IMF Tool cannot create OPLs.
A few syntax checks are implemented in case an existing package contains OPLs.
Supporting the creation of OPLs can be added, but there are no plans yet. Closing the issue for now.
