### ISSUE TITLE
API layer

### ISSUE THREAD

**Issue by acnhia** [IMFTool/IMFTool#19]
Is there a api (command line or web api) for IMF tool to integrate into script for orchestrating workflow?

**Comment by IMFTool** [comment]
There are a few command line options, see [Manual](https://github.com/IMFTool/IMFTool/tree/master/documentation):

Usage: IMF-Tool [options] IMF-Tool
Options:
-h, --help       Displays this help.
-v, --version. Displays version information.
-i, --imp-directory <directory> Open IMP in <directory> upon startup.
-a, --open-all-cpls.                    Open all CPLs from <directory> in Timeline View.

IMF Tool is an interactive GUI tool, the editing functionality is not exposed as an API.

**Comment by acnhia** [comment]
> There are a few command line options, see [Manual](https://github.com/IMFTool/IMFTool/tree/master/documentation):
> 
> Usage: IMF-Tool [options] IMF-Tool
> Options:
> -h, --help Displays this help.
> -v, --version. Displays version information.
> -i, --imp-directory Open IMP in upon startup.
> -a, --open-all-cpls. Open all CPLs from in Timeline View.
> 
> IMF Tool is an interactive GUI tool, the editing functionality is not exposed as an API.

thank you!

**Comment by fengliuxiaoxin** [comment]
excuse,  is there any plan to provide an api like command line to create new IMP?
