### ISSUE TITLE
IMF Video issue

### ISSUE THREAD

**Issue by WernerBleisteiner** [IMFTool/IMFTool#22]
Have another issue with a video. It's marked with X. Any suggestions decreasing fr or size won't do.
IMF created with most recent DaVinci Resolve Studio.
![ss-IMFTool-Video-Issue](https://user-images.githubusercontent.com/22868982/122057724-39766080-cdeb-11eb-8d60-8d529af83da6.png)
Export IMF from DVR  offers as codecs ProRes/easyDCP/KakaduJPEG200 - any incompatibilities here?

**Comment by wruppelx** [comment]
ProRes decoding is not supported by IMF Tool (yet).

**Comment by WernerBleisteiner** [comment]
Thanks. They I'll try any of the others :)
