### ISSUE TITLE
Marker can be beyond end of segment

### ISSUE THREAD

**Issue by matthewmarks-bbc** [IMFTool/IMFTool#23]
Thank you for IMF Tool. So far I'm finding it comprehensive, well-designed and reliable.

One thing I've discovered is that you can put a marker right at the end of a segment, or drag it there, which (I think!) actually corresponds to the first frame beyond the end of the segment. The CPL shows its `Offset` as being the same as the `SourceDuration` and when you re-open the IMP, it does not reappear on the timeline. Ideally the marker would be displayed as spanning the duration of a frame, rather than as infinitely narrow and at the start of a frame. I think this would clear up confusion about what actually refers to. But a quick fix would be to prevent it being put right at the end.

**Comment by wruppelx** [comment]
Thanks for pointing this out. 
Marker Offsets are limited to the range between zero edit units and the beginning of the last frame in each segment.
The GUI indeed allows for positioning a marker _after_ the last frame, which should be prevented.
I will add it to the TODO list.

**Comment by IMFTool** [comment]
Fixed via [ v1.8.364](https://github.com/IMFTool/IMFTool/releases/tag/v1.8.364)

**Comment by matthewmarks-bbc** [comment]
Thank you! Confirmed fixed. Sorry for not looking at this until now.
