### ISSUE TITLE
"Select MXF file" dialogue doesn't offer comprehensive navigation (at least on MacOS 10.14)

### ISSUE THREAD

**Issue by matthewmarks-bbc** [IMFTool/IMFTool#24]
This dialogue appears with `Add Asset` -> `Add existing MXF Track File`. It offers you a drop-down of every level of the current path, but you can't select any of the entries, nor the "Look in:" options, and the green "up arrow" button doesn't work either. I don't see a way of navigating freely around the filesystem, so had to put the assets in the working directory. There's a similar dialogue for sidecar assets, with similar issues. Contrast with opening a package, which brings up a native file browser.

The Mac I am using is running 10.14, so it's possible it works better in later versions of the OS.

**Comment by IMFTool** [comment]
This is actually a feature.
The reason behind is avoiding all kind of issues related to having IMF Tool copying (potentially very large) files in the user's file system, like access rights, limited disk space, slow network drives etc.
Instead, assets meant to be added to an IMP need to be copied to the respective IMP directory by the user.

From the user's manual (page 6):
<div>

  |   |  
-- | -- | --
  |   |  
  | Add existing MXF Track Files | Allows to add an existing MXF file to the IMP. The MXF file must upfront be copied into the IMP folder, or in a subfolder.Essence types JPEG 2000, PCM Audio and Timed Text are supported.If the modified IMP is exported as a Partial IMP, the imported MXF file(s) will be moved to the Partial IMP’s location.
</div>

I am not planning to change this.

**Comment by matthewmarks-bbc** [comment]
Oh - I didn't realise there was a manual! Testament to the product that we've got so far without having read it, but as you've gone to the trouble of producing one, I think it deserves to be made more obvious by being available from the application. I'll submit a feature request for that.

Now it's explained I understand the rationale. It's just a bit confusing when you're offered options (such as "Computer", home directory and all the parent directories) but clicking on them does nothing. Perhaps ideally an explanatory message would appear, but that's a very minor point so I'll close the issue.
