### ISSUE TITLE
Overwriting CPL can lead to broken package without warning

### ISSUE THREAD

**Issue by matthewmarks-bbc** [IMFTool/IMFTool#29]
I appreciate the warning when you choose to overwrite a CPL. However, there is an additional problem: doing this breaks the package due to its hash/size entries in the PKL changing. Although the write buttons are enabled by overwriting a CPL, a warning about unsaved changes is not given if you quit the application, leaving you with a broken package.

**Comment by IMFTool** [comment]
Fixed via [ v1.8.364](https://github.com/IMFTool/IMFTool/releases/tag/v1.8.364)

**Comment by matthewmarks-bbc** [comment]
Confirmed - thank you.
