### ISSUE TITLE
CPL "Issuer" field is copied into "Content Originator" field

### ISSUE THREAD

**Issue by matthewmarks-bbc** [IMFTool/IMFTool#31]
When you create a CPL, the value you enter in the dialogue for Issuer also appears in the Content Originator details and in the CPL. The value you enter for Content Originator appears to be lost.

Workaround: correct the field in the Details tab and overwrite the CPL.

**Comment by matthewmarks-bbc** [comment]
NB: I've discovered that if you don't put anything in the Content Originator field, it remains blank (which would be expected behaviour).

**Comment by IMFTool** [comment]
Fixed via [ v1.8.364](https://github.com/IMFTool/IMFTool/releases/tag/v1.8.364)
