### ISSUE TITLE
ADM Audio Track File not recognised

### ISSUE THREAD

**Issue by thomasheritage** [IMFTool/IMFTool#40]
Trying to add the ADM Audio Track file referenced in https://github.com/SMPTE/st2067-204/issues/3#issuecomment-2226939387 to an IMF Package results in:
![image](https://github.com/user-attachments/assets/b88ca080-6315-4bde-8f6f-fd37556d1828)

Having discussed this previously, the theory is that this is due to the position of the <axml> GSP in this file (as discussed in https://github.com/SMPTE/st2067-204/issues/4 -- this MXF file has this GSP at position (a)).

Note that analysing the above MXF with https://github.com/wruppelx/photon (with https://github.com/wruppelx/photon/pull/16 merged) results in zero errors.

**Comment by IMFTool** [comment]
GSP positions (a) and (b) as depicted in https://github.com/SMPTE/st2067-204/issues/4 are indeed not supported by asdcplib. I'll look into it, but I am not sure if position (b) is AS-02 compliant.
The audio MXF file referenced in https://github.com/SMPTE/st2067-204/issues/3#issuecomment-2226939387 is rejected because it is frame-wrapped audio.
IMF Audio Track Files shall be clip-wrapped per ST 2067-2.
(I agree the error message copied above should be more specific.)

**Comment by thomasheritage** [comment]
> I am not sure if position (b) is AS-02 compliant.

OK thanks -- something to be discussed as part of resolving https://github.com/SMPTE/st2067-204/issues/4

> rejected because it is frame-wrapped audio

I believe it is clip wrapped -- are there some aspects of the MXF file that indicate frame wrapping?

From the RegXML dump:

```
<r1:ContainerFormat>urn:smpte:ul:060e2b34.04010101.0d010301.02060200<!--MXFGCClipWrappedBroadcastWaveAudioData--></r1:ContainerFormat>
```

From inspecting the Body Partition containing the essence, there is:
```
  Key = 06 0E 2B 34 01 02 01 01 0D 01 03 01 16 01 02 00
  Length = 21888000

BWF audio #0
```
This Key is `WaveClipWrappedSoundElement` and it contains all of the audio essence.

My understanding was that this MXF file was being rejected by IMF-Tool purely because of the GSP position not being supported by asdcplib.

**Comment by IMFTool** [comment]
You are right. I think I have tested with the wrong file by mistake, apologies.
I have been working on a patch that makes IMF Tool accept the MXF file referenced in https://github.com/SMPTE/st2067-204/issues/3#issuecomment-2226939387 with the the GSP at position (a), drop me a PM if you want to test it.
If you also have a sample file for position (b), it would be great.
