### ISSUE TITLE
ADM Audio Track File -- summary box improvements

### ISSUE THREAD

**Issue by thomasheritage** [IMFTool/IMFTool#41]
A sample ADM Audio Track File in an IMP shows the following in the panel at the bottom left corner of the window:
![image](https://github.com/user-attachments/assets/dbfc01ad-e841-4691-b513-6842b1656ac4)

A regular Audio Track File shows:
![image](https://github.com/user-attachments/assets/7cb2bf87-e3b8-45b8-89c0-c8d8d863e8dc)

Suggested improvement for ADM Audio Track Files: make the left hand column as follows:
* Essence Type: ADM Audio
* Sample Rate: 48000 Hz
* Channels: 8
* Number of Soundfields: 2

i.e. a combination of the two

(This is because an ADM Audio Track File contains PCM audio in exactly the same way as a regular Audio Track File)

**Comment by IMFTool** [comment]
Addressed by 8912ba480b07f62ac77a311419b65b1d9e8850d9
