### ISSUE TITLE
.imf file example

### ISSUE THREAD

**Issue by ninuxi** [IMFTool/IMFTool#46]
hello
i would like to test your program. i can't find any .imf file online to try unpacking them.
does anyone have an .imf file to send me as a test?
thanks

**Comment by IMFTool** [comment]
A couple of IMF packages are available from Netflix [1]
e.g. [Meridian](http://download.opencontent.netflix.com.s3.amazonaws.com/Meridian/MERIDIAN_SHR_C_EN-XX_US-NR_51_LTRT_UHD_ML7_SL4_20160915_OV.zip) (Warning: 100 GB download)

[1] [https://opencontent.netflix.com](https://opencontent.netflix.com)
