### ISSUE TITLE
IAB track FPS mismatch with iab.mxf deliverable and video codec

### ISSUE THREAD

**Issue by WernerBleisteiner** [IMFTool/IMFTool#48]
Hi Wolfgang, 

tried to add a Dolby Atmos IAB track to a CPL. 
This does not work, stating that 50fps are required. 
DaVinci Resolve (18.6) as well as Dolby Conversion Tool can only create IAB.MXF @25fps.
However, the Video track used in IMF Tool (JPEG 2000) canneot be created in DVR @50fps.
Any suggestions how to solve this mismatch?
Thanks
![ss-IMF-TOOL-IAB-fps-mismatch](https://github.com/user-attachments/assets/e5820cf4-271c-421e-b467-afe07b283d48)

w

**Comment by wruppelx** [comment]
Hi Werner,
Thanks for using IMF Tool!
From ST 2067-201 §6.2:
"The IAB Virtual Track shall reference an IAB Track File whose Edit Rate, as defined in Section 5.4, is an integer multiple of the Edit Rate of the Main Image Virtual Track."
So it would not be compliant to add a 25 fps IAB Virtual Track to a 50 fps Image Virtual Track.

**Comment by WernerBleisteiner** [comment]
Yeah, I do understand that. 
The question is, which IMF Tool compaible video codec is to be used for 25 fps? 
Or is the issue rather, that IAB needs should comply with 50 fps?
(nothing serious, I'm just trying to explore different options)

**Comment by WernerBleisteiner** [comment]
Thanks, I'll try that.

But to talk also about success: 
Adding a S-ADM MPEG-H (ADM v2) track was easy!

Still have to explore to add ADM created with BBC's bmx tool. 
As the IMF Tool manual (p. 8 - Element #1 ) states also support for WAV, does this now include RF64 (Dolby) and BW64 (my [old issue ](url)https://github.com/IMFTool/IMFTool/issues/21). 
I suppose (non S-)ADM (Element #5) refers to the bmx-wrapped MXF?

**Comment by IMFTool** [comment]
> Adding a S-ADM MPEG-H (ADM v2) track was easy!

Great, thanks for sharing!
> Still have to explore to add ADM created with BBC's bmx tool.

I have reports that importing ADM track files created with bmx works.
> support for WAV, does this now include RF64 (Dolby) and BW64

Issue #21 is still open, indeed.

Ed.: The IMF Tool manual is available [here](documentation), and in the HELP menu of IMF Tool.

**Comment by WernerBleisteiner** [comment]
Solved my issue, byexporting  a JPEG2000 Kakadu @25fps mxf from DVR and added that to the original IMF package. 
So a new CPL with IAB and this works.
