### ISSUE TITLE
Missing annotations in  IMP Browser

### ISSUE THREAD

**Issue by WernerBleisteiner** [IMFTool/IMFTool#49]
When I add annotations in CPLs, they do not show up in the IMP Browser. Even after saving and re-opening the package. 
Am I missing a tweak? 
![ss-IMF-Tool-Lack-of-annotations](https://github.com/user-attachments/assets/26209de4-e176-4bac-a4a2-336f3e35f667)
Would be good to see them without opening an toggling between CPLs.

**Comment by IMFTool** [comment]
The Annotations in the IMP Browser are Asset-related and originate from the associated Packing List. 
IMF Tool does not support editing PKL annotations.

**Comment by WernerBleisteiner** [comment]
Thanks.
 Yeah, found out I can (and should) add annotations manually here (copy paste). 
All fine.
![ss-IMF-Tool-IMF-S-ADM-IAB-ADM-ASSETS-v1-2](https://github.com/user-attachments/assets/f4d42fa5-5784-4996-af9a-f09ba9cae9c1)



And now I have a nice package for the same test file containing ADM, S-ADM and IAB. Something to test a few things with.
