### ISSUE TITLE
Wrapping TimedText containing anc. assets using Win binary

### ISSUE THREAD

**Issue by weltwinkel** [IMFTool/IMFTool#5]
Wrapping of TimedText results in the following error message:
...
Wrapping Error:

1: Kumu error
The requested file does not exist on the system.
...
All neccesary files are located in the same folder as the .ttml file.

**Comment by IMFTool** [comment]
I confirm the Windows binary and build currently does not support ancillary data wrapping (i.e. IMSC1 image profile wrapping, and TTF wrapping in IMSC1 text profile) due to a limitation of asdcplib. We are working on a solution.

**Comment by IMFTool** [comment]
IMSC1 image profile wrapping has been fixed for Windows.
