### ISSUE TITLE
Audio distortion at the end

### ISSUE THREAD

**Issue by christosms74** [IMFTool/IMFTool#52]
Hi,

When I convert audio files to WAV format, it adds about 5 seconds of distortion at the end.

Best 

Christos

**Comment by IMFTool** [comment]
IMF Tool does not convert to WAV. 
Can you provide an example and further details on your workflow?

**Comment by christosms74** [comment]
Hi,

the conversion is to from WAV to MXF. 

Please see attached word file
[IMF TOOLS Documentation.docx](https://github.com/user-attachments/files/17570305/IMF.TOOLS.Documentation.docx)

**Comment by IMFTool** [comment]
Fixed by https://github.com/IMFTool/IMFTool/releases/tag/v1.9.387

**Comment by christosms74** [comment]
Thanks for your the quick support!!!
