### ISSUE TITLE
java not available - Exported CPL will not contain essence descriptors. IMF tool requires JDK 1.8 or higher.

### ISSUE THREAD

**Issue by jjos2000** [IMFTool/IMFTool#6]
Error specified in the subject is got every time I start the IMFtool software. 
I have upgraded the java release and have included it in the path variable both home java directory and bin directory, however I still get the same message. Can anyone provide some help on this?
Thanks in advance!

**Comment by IMFTool** [comment]
Can you please open a shell (Windows cmd.exe or a bash terminal on macOS/Linux), issue "java -version" and post the result?

FYI: In the upcoming release of IMFTool (scheduled until July 22) the dependency on java will be removed.

-Wolfgang

**Comment by jjos2000** [comment]
this is the ouput:
![image](https://user-images.githubusercontent.com/30261736/28316955-3e4c88be-6bc5-11e7-92cb-9835829160aa.png)

**Comment by jjos2000** [comment]
If it is tricky to be resolved, I'll wait for the next release :-)

**Comment by IMFTool** [comment]
The output looks good, you have the 64bit version of Java 1.8 installed.
Under Windows, no manual path settings are required, it is sufficient to install the JRE either 32 bit or 64 bit from the Oracle web site.

No idea why IMF Tool complains on your system.
In its current version, IMF Tool issues a "java -version" system call during startup to figure out installation and version of Java, exactly as you did in cmd.exe.
-Wolfgang

**Comment by jjos2000** [comment]
ok, so it is wise to wait for the new release on the 22nd.
Thanks!

**Comment by IMFTool** [comment]
Release V1.0.4 does not require Java anymore, so I close this issue.
